exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Google Sheet To Github Link Website"
description: > # this means to ignore newlines until "email:"
   A Hack Education & API Evangelist Production

email: info@contrafabulists.com
#blog logo
logo: "/tech-predictions/assets/images/cog.jpg"
logo2: "/tech-predictions/assets/images/cog_tr.png"
# blog cover
cover: "/tech-predictions/assets/images/owl.jpg"
covercredits: "http://bryanmmathers.com"

name: 'Contrafabulists'
author: 'Audrey Watters'
author_image: "/tech-predictions/assets/images/author_aw.jpg"
author2: 'Kin Lane'
author_image2: "/tech-predictions/assets/images/author_kl.jpg"

paginate:	1
paginate_path: "/page:num"
permalink: /:categories/:year/:month/:day/:title

url: "http://contrafabulists.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle:

# social icons and sharing options
social:
  - icon:   twitter
    url:    https://twitter.com/contrafabulists
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&url="

  - icon:   facebook
    url: https://facebook.com/contrafabulists
    desc: Like me on facebook
    share_url: http://www.facebook.com/sharer/sharer.php
    share_title: ?title=
    share_link: "?u="

  - icon:   github
    url:    https://github.com/Contrafabulists/website
    desc:   Fork me on github
    share_url:
    share_title:
    share_link:

 # - icon:  google-plus
 #   url:
 #   desc:
 #   share_url:
 #   share_title:
 #   share_link:

  - icon: rss
    url:  http://contrafabulists.com/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:info@contrafabulists.com
    desc: Email
    share_url:
    share_title:
    share_link:

theme: jekyll-theme-cayman